name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 6 * * *" # todo dia 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure assets folder
        run: mkdir -p assets

      - name: Fetch stats SVGs
        run: |
          curl -L "https://github-readme-stats.vercel.app/api?username=AlCristh&show_icons=true&hide_border=true&theme=tokyonight" \
            -o assets/github-stats.svg
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=AlCristh&layout=compact&hide_border=true&theme=tokyonight" \
            -o assets/top-langs.svg

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile stats"
          file_pattern: assets/*.svg
